---
- name: Test if cert exists
  stat:
    path: "{{item}}-cert.pub"
  register: signed_ssh_stat
  ignore_errors: yes
  check_mode: no
  changed_when: no
  with_items: "{{signed_ssh_keyfiles}}"
  tags:
    - ssh_signed_hostkeys

- include: sign.yml keyfile="{{signed_ssh_stat_keyfile.item}}"
  when: not signed_ssh_stat_keyfile.stat.exists
  with_items: "{{signed_ssh_stat.results}}"
  loop_control:
    loop_var: signed_ssh_stat_keyfile
  tags:
    - ssh_signed_hostkeys
