---
- name: Sign key
  community.hashi_vault.vault_write:
    auth_method: token
    token: "{{ login_data.login.auth.client_token }}"
    path: ssh-host-signer/sign/server
    data:
      cert_type: host
      ttl: "{{signed_ssh_valid_time}}"
      allowed_domains: "{{','.join(signed_ssh_hostnames)}}"
      public_key: "{{ lookup('ansible.builtin.file', {{signed_ssh_certfile.rstrip('-cert.pub')}}) }}"
    register: signed_key
  tags:
    - ssh_signed_hostkeys

- name: Write key to file
  ansible.builtin.copy:
    content: "{{signed_key}}"
    dest: "{{signed_ssh_certfile}}"
  tags:
    - ssh_signed_hostkeys

- name: File permissions
  file:
    path: "{{signed_ssh_certfile}}"
    owner: root
    group: root
    mode: a=r,u+w
  tags:
    - ssh_signed_hostkeys

- name: Add cert to sshd_config
  lineinfile:
    path: /etc/ssh/sshd_config
    line: "HostCertificate {{signed_ssh_certfile}}"
    regexp: "HostCertificate {{signed_ssh_certfile}}"
  notify: Restart SSH
  tags:
    - ssh_signed_hostkeys

- name: Remove signing cert
  file:
    path: "{{ssh_signed_tempfile.path}}"
    state: absent
  tags:
    - ssh_signed_hostkeys
