---
- name: Restart SSH
  systemd:
    name: ssh
    state: restarted
  when: ansible_service_mgr is 'systemd'
  tags:
    - ssh_signed_hostkeys

- name: Restart SSH
  service:
    name: ssh
    state: restarted
  when: ansible_service_mgr is not 'systemd'
  tags:
    - ssh_signed_hostkeys
